const TYPE_REDUCER = {
  CHANGE_VALUE: "CHANGE_VALUE",
  ADD_VALUE: "ADD_VALUE",
  EDIT_VALUE: "EDIT_VALUE",
  DELETE_VALUE: "DELETE_VALUE",
  SET_VALUE_API: "DELETE_VALUE",
  SET_NULL: "SET_NULL",
  SET_EMPTY: "SET_EMPTY",
};
Object.freeze(TYPE_REDUCER);
export default TYPE_REDUCER;
